version: "3.1"
services:
  dolar_api:
    container_name: dolar_hoy_api_container
    image: dyallo/dolar-hoy-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4500:4500"