name: Build and Deploy

on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - "tests/**"
      - "Dockerfile"
      - ".github/workflows/main.yml"
  pull_request:
    branches: [master]
    paths:
      - "src/**"
      - "tests/**"
      - "Dockerfile"
      - ".github/workflows/main.yml"

jobs:

  # lint_test:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip || (apt update && apt install -y python3-pip)
  #         pip install flake8 pytest
  #         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  #     - name: Lint with flake8
  #       run: |
  #         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  #         # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  #     - name: Test with pytest
  #       run: |
  #         pytest

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dolar-hoy-api:latest

  compose-up:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SSH into server, pull and restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /${{ secrets.USER }}/projects/dolar-hoy-api
            docker compose up -d
